travis:
  secure:
    BINSTAR_TOKEN: P3t3HdIKb/qw6yrLnerVvkh85btm643xXdf+I0sdEKMp6irqXFkTlFmBpaNBsZ4d/b0tJY/WEmabCYmNfqxoTH3QML8L9AAWkwFFX/UNFnX13tArFWul82DCwfPhM0q9JnI65BZo5s9up4IXa/5X2lR6gWTS/B3v0GyWicSkTAHf/aZ5dOKhewU3v3GCUwanQx2yoWd19FtQ5Mltwdw6m/qJVIEpu1XlifFgMOW4sJMdLcFAEJz+RAz2pXAK3nFBM8vB4nC4b42Z1QAKd2bwW2mOGUx8YIR9EvC55RV8jkKIvGN9IOizeyDcvtdstCRE4zukCw/Rj5Ay1lzHiDHqm6seNxU+iozuz+nGWk2A9oD8IwTQjciuavVGzR5nafUynj01ty43d7ADMrJOyF7P8SmGG2e38YvxepMAhysz0C9H6mL2ru+1v2AlcxxHFEXwfvZfdfO91PKE0jcI+m1MP0ophR7pdhkiGybhkkiWKR6pqdG6eL89d/jHObf+HKcqq1kfHsiTWj81WO+uDhprFGyVdikZz73njQCfeOWSzzzGVZ9H2cn2jqxMWCvWfzjL+1yazLAHIksA9viXT7eWbfORlpDhHwjoFyr7JmObG7IbGHOGSsYl4Hj/OBYUKlwy1j5WNH5rWCKXVKfsUqFo+x3CHnX8F97k4pnc/RGgnqY=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
